language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
script:
  - cargo build --verbose
  - cargo test --verbose
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ] ; then
     cargo bench --verbose;
    fi
